server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: member-service
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/members/**
            - id: class-service
              uri: lb://CLASS-SERVICE
              predicates:
                - Path=/api/classes/**
            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/api/bookings/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"

logging:
  file:
    name: /var/log/pulsefit/api-gateway.log
